---
master-password:
  type: string
  name: Master Password
  description: The password for any account that does not specify its own password
  nullable: false
  default:
    charset: "a-z,A-Z,0-9"
    len: 22
accounts:
  type: list
  subtype: object
  name: Accounts
  description: List of LND instances to manage
  range: "[1,*)"
  spec:
    uniqueBy: connection-settings
    displayAs: "{{name}}"
    spec:
      name:
        type: string
        name: Account Name
        description: Name of this account in the login list
        nullable: false
        default: Master
      connection-settings:
        # uniqueBy:
        #   any:
        #     - type
        #     - address
        #     - addressext
        #     - port
        #     - macaroon
        #     - certificate
        #     - lndconnect-url
        type: union
        name: Connection Settings
        tag:
          id: type
          name: Type
          description: |
            - Internal: The LND service installed to your Embassy
            - External: An LND node running on a different device
            - LNDConnect: An LNDConnect URL
          variantNames:
            internal: Internal
            external: External Manual
            lndconnect: External LNDConnect
        default: internal
        variants:
          internal:
            address:
              type: pointer
              name: Local IP
              description: The LAN IP address of your LND service
              subtype: app
              app-id: lnd
              target: lan-address
          external:
            addressext:
              type: string
              name: Public Address
              description: The public address of your LND node, NOTE that external tor nodes do not work yet.
              nullable: false
            port:
              type: number
              name: Port
              description: The gRPC port of your LND node
              nullable: false
              range: "[0,65535]"
              integral: true
              default: 10009
            macaroon:
              type: string
              name: Admin Macaroon
              description: Hex encoded admin macaroon from your LND node
              nullable: false
              pattern: ^[a-zA-Z0-9\/+]+$
              patternDescription: Must be a valid hexadecimal string
            certificate:
              type: string
              name: TLS Certificate
              description: Hex encoded tls certificate from your LND node
              nullable: false
              pattern: ^[a-zA-Z0-9\/+]+$
              patternDescription: Must be a valid hexadecimal string
          lndconnect:
            lndconnect-url:
              type: string
              name: LNDConnect URL
              description: LNDConnect URL for your external LND node
              nullable: false
              pattern: ^lndconnect:\/\/(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9]):[1-9][0-9]{0,4}[?](cert=[a-zA-Z0-9\-_]+&macaroon=[a-zA-Z0-9\-_]+|macaroon=[a-zA-Z0-9\-_]+&cert=[a-zA-Z0-9\-_]+)$
              patternDescription: Must be a valid LNDConnect URL
      password:
        type: string
        name: Password
        description: Account specific password to use in place of the master password
        nullable: true
  default:
    - name: Embassy LND
      connection-settings:
        type: internal
        address: null
